### ISSUE TITLE
Missing argument in POM patcher's code

### ISSUE THREAD

**Issue by marcomicera** [QMSTR/qmstr#535]
**Describe the bug**
Our [POM patcher initContainer](https://github.com/endocode/qmstr/blob/10687250fbd0c06cb3e88365a31271caa0f3eb09/deploy/qmstr/base/job.yaml#L65-L70) fails for some repositories, like:
- [github.com/hope-for/hope-boot](https://github.com/hope-for/hope-boot)
- [github.com/lrwinx/shop](https://github.com/lrwinx/shop)
- [github.com/Ardesco/Selenium-Maven-Template](https://github.com/Ardesco/Selenium-Maven-Template)
- [github.com/strongbox/strongbox](https://github.com/strongbox/strongbox)
- [github.com/IanDarwin/Android-Cookbook-Examples](https://github.com/IanDarwin/Android-Cookbook-Examples) (> 50 MB)

Here's its log:

```
$ kubectl logs --follow $(kubectl get pods --selector job-name=qmstr -o=name) pom-patch
WARNING:root:Multiple POM files found. Using /home/configure/buildroot/rev-d8d11858410a92e15ec3345b07d93b217861a00a/pom.xml.
Traceback (most recent call last):
  File "insert-build-plugin.py", line 105, in <module>
    exit(int(insert_build_plugin()))
  File "/home/configure/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/configure/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/configure/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/configure/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "insert-build-plugin.py", line 52, in insert_build_plugin
    plugin_section = ET.SubElement(build_section)
TypeError: SubElement() takes at least 2 arguments (1 given)
```

**To Reproduce**
1. Move to the [`deploy` folder](https://github.com/endocode/qmstr/tree/feature/self-contained-modules/deploy):
    ```bash
    cd deploy
    ```
1. Deploy our DGraph StatefulSet:
    ```bash
    kubectl apply -k dgraph
    ``` 
1. Explicitly specify all Docker image tags to enable manual deployment in [`deploy/qmstr/kustomization.yaml`](https://github.com/endocode/qmstr/blob/feature/self-contained-modules/deploy/qmstr/kustomization.yaml):
    ```yaml
    # In case of manual deployment, insert the desired image tags here.
    images:
      - name: endocodeci/qmstr-master
        newTag: sha-1068725
      - name: endocodeci/qmstr-client-mvn
        newTag: sha-1068725
      - name: endocodeci/pom-patch
        newTag: sha-1068725
    ```
1. Override the repository URL in [`deploy/qmstr/repo-url.yaml`](https://github.com/endocode/qmstr/blob/feature/self-contained-modules/deploy/qmstr/repo-url.yaml).\
The patch will be automatically applied by Kustomize.
1. Deploy QMSTR:
    ```bash
    kubectl apply -k qmstr
    ```

**Expected behavior**
The initContainer should run to completion, letting the other two containers being their execution.

**Where the error is**
[This method](https://github.com/endocode/qmstr/blob/10687250fbd0c06cb3e88365a31271caa0f3eb09/lib/pyqmstr/pom-patch/insert-build-plugin.py#L52) requires two parameters, but only one is supplied.\
`'build'` does not make it work.

**Comment by marcomicera** [comment]
Fixed in https://github.com/endocode/qmstr/commit/1006cb936bf2a1cd2539d8ae00a067861328b400.
